In [1]:
import pandas as pd
from scipy import stats
from statistics import mean

In [2]:
df = pd.read_csv('../data/nifty_smallcap_250_ratios.csv')
df = df[df['roe']>0]
df = df[df['ev_ebitda']>0]
df = df[df['pe_ratio']>0]
df.head()

       SYMBOL       INSTRUMENT_KEY    pe_ratio      roe  ev_ebitda
0  CHENNPETRO  NSE_EQ|INE178A01016   53.776154  0.02515     12.658
1      MASTEK  NSE_EQ|INE759A01021   21.141436  0.16525     13.665
2    SAPPHIRE  NSE_EQ|INE806T01020  552.049200  0.01221     25.073
4    NIVABUPA  NSE_EQ|INE995S01015   70.875000  0.07392     44.085
5  KIRLOSBROS  NSE_EQ|INE732A01036   44.642174  0.21890     29.883

In [3]:
pe_ratio_percentile = []
ev_ebitda_percentile = []
for idx in df.index:
    pe_ratio_percentile.append(stats.percentileofscore(df['pe_ratio'], df.loc[idx, 'pe_ratio'])/100)
    ev_ebitda_percentile.append(stats.percentileofscore(df['ev_ebitda'], df.loc[idx, 'ev_ebitda'])/100)

df['ev_ebitda_percentile'] = ev_ebitda_percentile
df['pe_ratio_percentile'] = pe_ratio_percentile

In [4]:
df

,SYMBOL,INSTRUMENT_KEY,pe_ratio,roe,ev_ebitda,ev_ebitda_percentile,pe_ratio_percentile
0,CHENNPETRO,NSE_EQ|INE178A01016,53.776154,0.02515,12.658,0.143564,0.618812
1,MASTEK,NSE_EQ|INE759A01021,21.141436,0.16525,13.665,0.178218,0.153465
2,SAPPHIRE,NSE_EQ|INE806T01020,552.049200,0.01221,25.073,0.485149,0.990099
4,NIVABUPA,NSE_EQ|INE995S01015,70.875000,0.07392,44.085,0.856436,0.792079
5,KIRLOSBROS,NSE_EQ|INE732A01036,44.642174,0.21890,29.883,0.584158,0.490099
...,...,...,...,...,...,...,...
201,ASTERDM,NSE_EQ|INE914M01019,103.118900,0.07756,39.568,0.772277,0.920792
202,LTFOODS,NSE_EQ|INE818H01020,27.928366,0.16807,16.891,0.252475,0.277228
203,IKS,NSE_EQ|INE115Q01022,55.862190,0.32981,35.645,0.702970,0.648515
204,KFINTECH,NSE_EQ|INE138Y01010,67.128044,0.26100,43.683,0.846535,0.772277
205,DCMSHRIRAM,NSE_EQ|INE499A01024,34.963882,0.08935,15.615,0.222772,0.361386

In [5]:
value_score = []

for idx in df.index:
    value_score.append(mean([df.loc[idx, 'pe_ratio_percentile'], df.loc[idx, 'ev_ebitda_percentile']]))

df['value_score'] = value_score

In [6]:
df.sort_values(by='value_score', inplace=True)
df

,SYMBOL,INSTRUMENT_KEY,pe_ratio,roe,ev_ebitda,ev_ebitda_percentile,pe_ratio_percentile,value_score
7,GESHIP,NSE_EQ|INE017A01032,6.305316,0.17589,3.047,0.004950,0.009901,0.007426
106,KNRCON,NSE_EQ|INE634I01029,6.289245,0.24926,4.736,0.014851,0.004950,0.009901
91,JINDALSAW,NSE_EQ|INE324A01032,8.555841,0.14350,5.573,0.019802,0.014851,0.017327
11,NATCOPHARM,NSE_EQ|INE987B01026,9.487885,0.27974,6.359,0.024752,0.024752,0.024752
46,BBTC,NSE_EQ|INE050A01025,12.330641,0.30411,4.730,0.009901,0.039604,0.024752
...,...,...,...,...,...,...,...,...
99,ASTRAZEN,NSE_EQ|INE203A01020,196.090060,0.15617,85.720,0.965347,0.970297,0.967822
49,SIGNATURE,NSE_EQ|INE903U01023,172.386220,0.14894,412.758,0.995050,0.960396,0.977723
78,DELHIVERY,NSE_EQ|INE148O01028,181.441850,0.01745,333.751,0.990099,0.965347,0.977723
43,PTCIL,NSE_EQ|INE596F01018,357.180540,0.06005,317.019,0.985149,0.985149,0.985149
174,FACT,NSE_EQ|INE188A01015,1425.075700,0.03002,656.453,1.000000,1.000000,1.000000

In [7]:
portfolio = df[:25]
portfolio.set_index('SYMBOL')

,INSTRUMENT_KEY,pe_ratio,roe,ev_ebitda,ev_ebitda_percentile,pe_ratio_percentile,value_score
SYMBOL,,,,,,,
GESHIP,NSE_EQ|INE017A01032,6.305316,0.17589,3.047,0.004950,0.009901,0.007426
KNRCON,NSE_EQ|INE634I01029,6.289245,0.24926,4.736,0.014851,0.004950,0.009901
JINDALSAW,NSE_EQ|INE324A01032,8.555841,0.14350,5.573,0.019802,0.014851,0.017327
NATCOPHARM,NSE_EQ|INE987B01026,9.487885,0.27974,6.359,0.024752,0.024752,0.024752
BBTC,NSE_EQ|INE050A01025,12.330641,0.30411,4.730,0.009901,0.039604,0.024752
SCI,NSE_EQ|INE109A01011,12.226946,0.10644,6.750,0.029703,0.034653,0.032178
PNCINFRA,NSE_EQ|INE195J01029,9.625669,0.14595,7.189,0.034653,0.029703,0.032178
JUSTDIAL,NSE_EQ|INE599M01018,13.586402,0.13539,8.115,0.049505,0.054455,0.051980
MAHSEAMLES,NSE_EQ|INE271B01025,12.902308,0.12880,8.628,0.064356,0.049505,0.056931
CHAMBLFERT,NSE_EQ|INE085A01013,13.678970,0.20656,8.734,0.074257,0.059406,0.066832
GNFC,NSE_EQ|INE113A01013,13.755851,0.07072,8.635,0.069307,0.064356,0.066832
MGL,NSE_EQ|INE002S01010,14.640722,0.18866,8.586,0.059406,0.074257,0.066832
GSPL,NSE_EQ|INE246F01010,17.005075,0.10939,7.571,0.039604,0.103960,0.071782
NCC,NSE_EQ|INE868B01028,17.210566,0.12131,7.646,0.044554,0.108911,0.076733
GPIL,NSE_EQ|INE177H01039,13.795317,0.17132,9.427,0.084158,0.069307,0.076733
NAVA,NSE_EQ|INE725A01030,16.206255,0.16193,10.224,0.103960,0.089109,0.096535
TANLA,NSE_EQ|INE483C01032,16.978228,0.24099,11.332,0.118812,0.099010,0.108911
JKTYRE,NSE_EQ|INE573A01042,20.368217,0.10622,8.817,0.079208,0.143564,0.111386
VTL,NSE_EQ|INE825A01020,15.874048,0.09259,11.865,0.138614,0.084158,0.111386
ARE&M,NSE_EQ|INE885A01032,18.760899,0.13317,10.770,0.108911,0.123762,0.116337
EIDPARRY,NSE_EQ|INE126A01031,22.223124,0.14683,8.429,0.054455,0.178218,0.116337
WELCORP,NSE_EQ|INE191B01025,12.853693,0.28259,14.280,0.193069,0.044554,0.118812
ZEEL,NSE_EQ|INE256A01028,20.583800,0.06135,10.009,0.094059,0.148515,0.121287
REDINGTON,NSE_EQ|INE891D01026,15.197271,0.21345,13.320,0.163366,0.079208,0.121287
ROUTE,NSE_EQ|INE450U01017,20.122408,0.14409,10.777,0.113861,0.138614,0.126238

In [9]:
portfolio.to_csv('../data/portfolio.csv', index=False)